export type FlashType = "Sheet" | "Custom" | "Guest" | "Hybrid" | "Walk-In";

export interface Club {
  id: string;
  name: string;
  quickLink?: string;
  avgFlashLength: number; // minutes
  flashType: FlashType;
  avgPrice: number; // dollars
  sfwFriendly: boolean;
  sfwActive: boolean;
  invSpeed: number; // 1-10
  yeetSpeed: number; // 1-10
  preparedness: number; // 1-10
  avgRating: number; // 1-5
  comments: string;
  clubAge: number; // years
}

export const CLUBS: Club[] = [
  {
    id: "1",
    name: "Thunderstrike Ink",
    quickLink: "https://example.com/thunderstrike",
    avgFlashLength: 45,
    flashType: "Sheet",
    avgPrice: 120,
    sfwFriendly: true,
    sfwActive: true,
    invSpeed: 8,
    yeetSpeed: 7,
    preparedness: 9,
    avgRating: 4.8,
    comments: "Incredible atmosphere and lightning-fast setup. Always prepared with fresh flash sheets every session.",
    clubAge: 6,
  },
  {
    id: "2",
    name: "Storm Cell Studio",
    quickLink: "https://example.com/stormcell",
    avgFlashLength: 60,
    flashType: "Custom",
    avgPrice: 200,
    sfwFriendly: true,
    sfwActive: false,
    invSpeed: 6,
    yeetSpeed: 5,
    preparedness: 8,
    avgRating: 4.5,
    comments: "Premium custom work at a premium price. Slower pace but the quality is unmatched.",
    clubAge: 10,
  },
  {
    id: "3",
    name: "Voltage Vaults",
    quickLink: undefined,
    avgFlashLength: 30,
    flashType: "Walk-In",
    avgPrice: 80,
    sfwFriendly: false,
    sfwActive: false,
    invSpeed: 9,
    yeetSpeed: 9,
    preparedness: 6,
    avgRating: 3.9,
    comments: "High energy walk-in spot. No-frills, fast turnaround. Not always the cleanest setup but gets the job done.",
    clubAge: 3,
  },
  {
    id: "4",
    name: "Nimbus Needle Co.",
    quickLink: "https://example.com/nimbus",
    avgFlashLength: 50,
    flashType: "Hybrid",
    avgPrice: 150,
    sfwFriendly: true,
    sfwActive: true,
    invSpeed: 7,
    yeetSpeed: 6,
    preparedness: 9,
    avgRating: 4.6,
    comments: "Best of both worlds — hybrid flash with custom add-ons available. Super organized and welcoming.",
    clubAge: 5,
  },
  {
    id: "5",
    name: "Static Parlor",
    quickLink: "https://example.com/static",
    avgFlashLength: 40,
    flashType: "Guest",
    avgPrice: 175,
    sfwFriendly: true,
    sfwActive: true,
    invSpeed: 5,
    yeetSpeed: 4,
    preparedness: 7,
    avgRating: 4.2,
    comments: "Rotating guest artists keep the flash fresh. Booking can be slow but the talent level is consistently high.",
    clubAge: 8,
  },
  {
    id: "6",
    name: "Cirrus Collective",
    quickLink: undefined,
    avgFlashLength: 35,
    flashType: "Sheet",
    avgPrice: 100,
    sfwFriendly: false,
    sfwActive: true,
    invSpeed: 8,
    yeetSpeed: 8,
    preparedness: 7,
    avgRating: 4.0,
    comments: "Affordable sheet flash with solid execution. Not SFW-friendly but they are upfront about it.",
    clubAge: 2,
  },
  {
    id: "7",
    name: "Squall & Ink",
    quickLink: "https://example.com/squall",
    avgFlashLength: 55,
    flashType: "Custom",
    avgPrice: 250,
    sfwFriendly: true,
    sfwActive: false,
    invSpeed: 4,
    yeetSpeed: 3,
    preparedness: 10,
    avgRating: 4.9,
    comments: "Top-tier custom work. Extremely thorough consultation process. Worth the wait and price for serious pieces.",
    clubAge: 14,
  },
  {
    id: "8",
    name: "Overcast Arts",
    quickLink: "https://example.com/overcast",
    avgFlashLength: 25,
    flashType: "Walk-In",
    avgPrice: 60,
    sfwFriendly: true,
    sfwActive: true,
    invSpeed: 10,
    yeetSpeed: 10,
    preparedness: 5,
    avgRating: 3.6,
    comments: "Fastest in-and-out in the city. Flash selection is hit or miss but prices are unbeatable for beginners.",
    clubAge: 1,
  },
  {
    id: "9",
    name: "Hailstorm Heavy",
    quickLink: "https://example.com/hailstorm",
    avgFlashLength: 70,
    flashType: "Hybrid",
    avgPrice: 180,
    sfwFriendly: false,
    sfwActive: false,
    invSpeed: 6,
    yeetSpeed: 7,
    preparedness: 8,
    avgRating: 4.3,
    comments: "Bold heavy-line style specialists. The hybrid approach works well here — semi-custom feel at sheet prices.",
    clubAge: 7,
  },
  {
    id: "10",
    name: "Tempest Tattoo Guild",
    quickLink: "https://example.com/tempest",
    avgFlashLength: 45,
    flashType: "Guest",
    avgPrice: 200,
    sfwFriendly: true,
    sfwActive: true,
    invSpeed: 5,
    yeetSpeed: 5,
    preparedness: 9,
    avgRating: 4.7,
    comments: "Prestigious guest rotation with artists from across the region. Prep work is meticulous and communication is excellent.",
    clubAge: 11,
  },
  {
    id: "11",
    name: "Drizzle & Draft",
    quickLink: undefined,
    avgFlashLength: 20,
    flashType: "Sheet",
    avgPrice: 75,
    sfwFriendly: true,
    sfwActive: true,
    invSpeed: 9,
    yeetSpeed: 8,
    preparedness: 6,
    avgRating: 3.8,
    comments: "Fun casual vibe, great for small quick pieces. Flash sheets are decent but limited in variety.",
    clubAge: 4,
  },
  {
    id: "12",
    name: "Anvil Cloud Studio",
    quickLink: "https://example.com/anvil",
    avgFlashLength: 60,
    flashType: "Custom",
    avgPrice: 300,
    sfwFriendly: true,
    sfwActive: false,
    invSpeed: 3,
    yeetSpeed: 2,
    preparedness: 10,
    avgRating: 5.0,
    comments: "The gold standard for custom work in the area. Waitlist is 6+ months but every piece is a masterpiece.",
    clubAge: 16,
  },
];
